[package]
name = "git-todo"
version = "0.1.0"
edition = "2021"

[dependencies]
im = {version = "15.1.0"}
floem = { git = "https://github.com/lapce/floem.git" }
rusqlite = { version = "0.31.0", features = ["bundled"] }
